use techshop2;
-- SQL query to retrieve a list of all orders along with customer information  
select orderid, (select f_name  from customers where customers.customerid=orders.customerid)as customername,
(select productname from products where products.productid=(select productid from orderdetails where orders.orderid=orderdetails.orderid limit 1))as productPurchased
from orders ;

-- SQL query to find the total revenue generated by each electronic gadget product. 
select p.productname as prod_purchased,
sum(od.quantity*p.price) as revenue from products p
join orderdetails od on od.productid=p.productid 
group by productname; 

-- SQL query to list all customers who have made at least one purchase. 
select c.f_name as customer, c.phone as Cphone, c.address as Caddress, count(orderid) as total_orders from customers c
join orders o on c.customerid=o.customerid group by c.f_name,c.phone,c.address;

-- SQL query to find the most popular electronic gadget, which is the one with the highest 
select p.productname as HighPurchased_Gadget, sum(od.quantity) as total_quantity from products p
join orderdetails od on od.productid=p.productid  
join orders o on o.orderid=od.orderid
where o.ostatus not in("cancelled")group by p.productname  order by total_quantity  desc limit 1 ;

select p.productname as HighPurchased_Gadget, sum(od.quantity) as total_quantity from products p
join orderdetails od on od.productid=p.productid  
group by p.productname  order by total_quantity  desc limit 1 ;

-- SQL query to retrieve a list of electronic gadgets along with their corresponding categories.
select productname, category from products;

--  SQL query to calculate the average order value for each customer. Include the customer's name and their average order value.
select c.f_name as customername ,avg(o.totalamount) as avg_orderValue from orders o 
join customers c on o.customerid=c.customerid group by c.f_name;

--  SQL query to find the order with the highest total revenue. Include the order ID, customer information, and the total revenue. 
select c.f_name as customername,
c.email as customeremail,
o.orderid as orderid,
o.totalamount as hightotalRevenue from orders o join customers c on
o.customerid=c.customerid order by o.totalamount desc limit 1;

-- SQL query to list electronic gadgets and the number of times each product has been ordered.
select p.productname as gadget, p.category, count(od.orderid) from products p 
join orderdetails od on od.productid=p.productid group by p.productname, p.category;

--  SQL query to find customers who have purchased a specific electronic gadget product. Allow users to input the product name as a parameter. 
select c.f_name as customers, p.productname as gadget, od.customerid as cust_id from orderdetails od
join customers c on c.customerid=od.customerid 
join products p on od.productid=p.productid
where p.productname="Smartwatch";

-- SQL query to calculate the total revenue generated by all orders placed within a specific time period. Allow users to input the start and end dates as parameters. 
select  sum(totalamount) as totalRevenue from orders where orderdate between  "2025-03-02" and "2025-03-07";


